facts = [
    "🛠️ Minecraft was created by Markus Persson, also known as Notch.",
    "📅 The first version of Minecraft was released on May 17, 2009.",
    "😱 Creepers were a result of a coding error. Notch wanted to create a pig but ended up with the Creeper’s design.",
    "🗣️ The Enderman language is actually English in reverse.",
    "🔢 There are over 400 unique items in Minecraft.",
    "🌍 Minecraft's world is made up of roughly 60 million blocks.",
    "🐱 Ghasts sound like cats because the sounds were made by C418's cat.",
    "💀 The Wither boss drops a Nether Star upon defeat.",
    "🧱 Endermen can pick up and move blocks.",
    "🐖 You can ride a pig with a saddle.",
    "👾 There are more than 150 different types of mobs in Minecraft.",
    "⏱️ The world record for the fastest speedrun in Minecraft is under 15 minutes.",
    "🌐 Minecraft has been sold in all countries except Antarctica.",
    "🎮 The game was inspired by several other games, including Dwarf Fortress and Dungeon Keeper.",
    "🏆 Minecraft is the best-selling video game of all time.",
    "🎮 There are multiple game modes in Minecraft: Survival, Creative, Adventure, and Spectator.",
    "🔌 Redstone in Minecraft is inspired by electrical engineering concepts.",
    "🏫 The game has an education edition used in schools to teach subjects like math and history.",
    "🎶 Minecraft's music was composed by Daniel Rosenfeld, also known as C418.",
    "🦴 There is a rare chance to find fossils underground in Minecraft.",
    "🌲 The game has several biomes, including deserts, jungles, and oceans.",
    "🧪 You can brew potions using various ingredients found in the game.",
    "🛠️ Minecraft has a strong modding community that creates custom content for the game.",
    "🎉 The game has its own conventions, like Minecon, where fans gather to celebrate.",
    "🔧 Players can build complex machines and structures using redstone circuits.",
    "🐉 The Ender Dragon is the final boss in the game.",
    "🌍 Minecraft has been used to recreate real-world locations and historical sites.",
    "💡 The game encourages creativity and problem-solving skills.",
    "🎁 There are hidden Easter eggs and references in the game.",
    "🐺 Players can tame wolves and ocelots as pets.",
    "🌋 Minecraft's Nether dimension is a dangerous place filled with lava and hostile mobs.",
    "🎬 The game has been adapted into several books and a movie.",
    "🛡️ Minecraft has various difficulty levels, from peaceful to hardcore.",
    "💎 The game features many types of ores, including diamonds, emeralds, and netherite.",
    "🎨 Players can create custom skins for their characters.",
    "🏆 There are achievements and advancements to unlock in the game.",
    "📚 Minecraft has been praised for its educational value and creativity.",
    "🌲 The game's terrain is generated procedurally, making each world unique.",
    "💻 Minecraft's code is written in Java and has been ported to other languages.",
    "🌿 There are many different types of trees and plants in the game.",
    "🌐 The game features multiplayer modes where players can collaborate or compete.",
    "🏡 Minecraft's villages are populated by NPCs called villagers.",
    "🗣️ The game has been translated into multiple languages.",
    "🎣 Players can fish for items and food in Minecraft.",
    "🍲 There are different types of food to eat, each with unique effects.",
    "🐟 Minecraft's oceans are home to various aquatic creatures and shipwrecks.",
    "🗺️ The game has a built-in map editor called Minecraft Realms.",
    "🔨 Players can craft a variety of tools and weapons using different materials.",
    "🎨 Minecraft has a creative mode where players have unlimited resources.",
    "🎮 The game's graphics are intentionally pixelated to give it a retro look.",
    "🎶 Minecraft's music and sound effects add to its immersive experience.",
    "🔍 There are secret structures like jungle temples and ocean monuments.",
    "🏙️ Minecraft has been used to build large-scale projects, including cities and monuments.",
    "🛠️ The game's mechanics include hunger and health systems.",
    "🏆 Minecraft has received numerous awards and accolades.",
    "🗺️ There are custom maps and adventure maps created by the community.",
    "🌲 Minecraft's survival mode challenges players to gather resources and survive.",
    "⛈️ The game has a weather system, including rain and thunderstorms.",
    "🎨 Players can dye and customize their armor and tools.",
    "🌍 Minecraft has various dimensions, including the Overworld, Nether, and End.",
    "🎮 The game has been released on multiple platforms, including PC, consoles, and mobile devices.",
    "🛒 Players can trade with villagers for useful items.",
    "🔨 Minecraft has a complex crafting system with hundreds of recipes.",
    "🚂 There are different types of transportation, including boats and minecarts.",
    "🎥 The game has been featured in many popular YouTube videos and streams.",
    "🧱 Minecraft has a variety of block types, each with unique properties.",
    "🎮 The game has inspired numerous spin-offs and adaptations.",
    "🗺️ Players can create their own custom worlds and share them with others.",
    "🟫 Minecraft's blocky world is composed of cubes with different textures.",
    "🌐 The game has a vibrant and active online community.",
    "👾 Minecraft has various mobs, including zombies, skeletons, and spiders.",
    "🛠️ Players can enchant their tools and weapons for special abilities.",
    "🌳 The game has different types of wood, each with unique properties.",
    "🌞 Minecraft has a day-night cycle that affects gameplay.",
    "🌾 Players can build automated farms and machines using redstone.",
    "📜 The game has a rich lore and backstory created by the community.",
    "🎨 Minecraft's creative mode allows for limitless building possibilities.",
    "🌲 The game has various biomes, each with unique resources and challenges.",
    "🌍 Minecraft's world is divided into chunks for efficient loading.",
    "🔧 The game has various game mechanics, including physics and fluid dynamics.",
    "🌍 Minecraft's world is virtually infinite, with over 30 million blocks in each direction.",
    "🎓 The game has inspired educational programs and initiatives.",
    "🔧 Players can use command blocks to automate tasks and create mini-games.",
    "🧪 Minecraft has various types of potions with different effects.",
    "🎮 The game has a thriving modding community that extends its features.",
    "⛏️ Players can find and explore abandoned mineshafts and dungeons.",
    "📸 Minecraft has a built-in screenshot function to capture creations.",
    "🎨 The game's creative mode is often used for architectural and artistic projects.",
    "🗿 Minecraft has different types of stone, each with unique properties.",
    "🛡️ Players can create and customize banners for decoration.",
    "🛡️ The game has various types of armor for protection.",
    "⛏️ Minecraft's mechanics include smelting and cooking processes.",
    "💡 The game has a dynamic lighting system that affects visibility.",
    "🐷 Players can breed animals for food and resources.",
    "⚔️ Minecraft has a complex combat system with different weapons and tactics.",
    "🌿 The game has various types of plants and crops for farming.",
    "🔮 Minecraft's enchanting system allows for powerful upgrades.",
    "🎨 The game has a variety of decorative blocks for building.",
    "🔍 Minecraft's world is filled with secrets and hidden features.",
    "🎵 Players can create music using note blocks.",
    "🎣 The game has various types of fish and fishing mechanics.",
    "🌍 Minecraft has different types of biomes, each with unique flora and fauna.",
    "🔧 The game's redstone mechanics allow for complex circuitry and automation.",
    "🌟 Minecraft has been praised for its open-ended gameplay and creativity.",
    "🗺️ Players can create and explore custom adventure maps.",
    "🌧️ The game has various weather effects, including snow and rain.",
    "🌍 Minecraft's terrain generation creates unique landscapes and caves.",
    "🚤 Players can use boats to travel across water bodies.",
    "🎶 The game has a detailed and immersive sound design.",
    "🔧 Minecraft's modding community has created thousands of mods and custom content.",
    "⛏️ The game's resource management mechanics add depth to gameplay.",
    "🌲 Minecraft has a variety of biomes, each with unique challenges and resources.",
    "🎨 Players can create custom skins for their characters.",
    "🌍 The game's procedural generation ensures that no two worlds are the same.",
    "💎 Minecraft has various types of ores, each with unique uses.",
    "🎮 The game has a creative mode for unlimited building possibilities.",
    "🔧 Players can build complex machines and contraptions using redstone.",
    "🌦️ Minecraft has a dynamic weather system that affects gameplay.",
    "👾 The game has various types of mobs, each with unique behaviors.",
    "🌋 Players can explore vast underground cave systems.",
    "🧱 Minecraft has a variety of decorative blocks for building.",
    "🎮 The game's modding community has created custom content and enhancements.",
    "🚂 Players can use minecarts and rails for transportation.",
    "🌐 Minecraft has a thriving online multiplayer community.",
    "🌿 The game has various types of plants and crops for farming.",
    "🛒 Players can trade with villagers for valuable items.",
    "⚔️ Minecraft has a complex combat system with different weapons and tactics.",
    "🔮 The game's enchanting system allows for powerful upgrades.",
    "🗺️ Players can create custom maps and share them with others.",
    "🎶 Minecraft has a rich and immersive sound design.",
    "🧱 The game has various types of blocks, each with unique properties.",
    "🧭 Players can explore abandoned mineshafts and dungeons.",
    "💡 Minecraft has a detailed and realistic lighting system.",
    "🛠️ The game's resource management mechanics add depth to gameplay.",
    "🛡️ Players can create and customize banners for decoration.",
    "🌍 Minecraft has a variety of biomes, each with unique flora and fauna.",
    "🔧 The game's redstone mechanics allow for complex circuitry and automation.",
    "🎨 Players can create custom skins for their characters.",
    "⛏️ Minecraft has various types of ores, each with unique uses.",
    "🎮 The game has a creative mode for unlimited building possibilities.",
    "🔧 Players can build complex machines and contraptions using redstone.",
    "🌦️ Minecraft has a dynamic weather system that affects gameplay.",
    "👾 The game has various types of mobs, each with unique behaviors.",
    "🌋 Players can explore vast underground cave systems.",
    "🧱 Minecraft has a variety of decorative blocks for building.",
    "🎮 The game's modding community has created custom content and enhancements.",
    "🚂 Players can use minecarts and rails for transportation.",
    "🌐 Minecraft has a thriving online multiplayer community.",
    "🌿 The game has various types of plants and crops for farming.",
    "🛒 Players can trade with villagers for valuable items.",
    "⚔️ Minecraft has a complex combat system with different weapons and tactics.",
    "🔮 The game's enchanting system allows for powerful upgrades.",
    "🗺️ Players can create custom maps and share them with others.",
    "🎶 Minecraft has a rich and immersive sound design.",
    "🧱 The game has various types of blocks, each with unique properties.",
    "🧭 Players can explore abandoned mineshafts and dungeons.",
    "💡 Minecraft has a detailed and realistic lighting system.",
    "🛠️ The game's resource management mechanics add depth to gameplay.",
    "🛡️ Players can create and customize banners for decoration.",
    "🌍 Minecraft has a variety of biomes, each with unique flora and fauna.",
    "🔧 The game's redstone mechanics allow for complex circuitry and automation.",
    "🎨 Players can create custom skins for their characters.",
    "⛏️ Minecraft has various types of ores, each with unique uses.",
    "🎮 The game has a creative mode for unlimited building possibilities.",
    "🔧 Players can build complex machines and contraptions using redstone.",
    "🌦️ Minecraft has a dynamic weather system that affects gameplay.",
    "👾 The game has various types of mobs, each with unique behaviors.",
    "🌋 Players can explore vast underground cave systems.",
    "🧱 Minecraft has a variety of decorative blocks for building.",
    "🎮 The game's modding community has created custom content and enhancements.",
    "🚂 Players can use minecarts and rails for transportation.",
    "🌐 Minecraft has a thriving online multiplayer community.",
    "🌿 The game has various types of plants and crops for farming.",
    "🛒 Players can trade with villagers for valuable items.",
    "⚔️ Minecraft has a complex combat system with different weapons and tactics.",
    "🔮 The game's enchanting system allows for powerful upgrades.",
    "🗺️ Players can create custom maps and share them with others.",
    "🎶 Minecraft has a rich and immersive sound design.",
    "🧱 The game has various types of blocks, each with unique properties.",
    "🧭 Players can explore abandoned mineshafts and dungeons.",
    "💡 Minecraft has a detailed and realistic lighting system.",
    "🛠️ The game's resource management mechanics add depth to gameplay.",
    "🛡️ Players can create and customize banners for decoration.",
    "🌍 Minecraft has a variety of biomes, each with unique flora and fauna.",
    "🔧 The game's redstone mechanics allow for complex circuitry and automation.",
    "🎨 Players can create custom skins for their characters.",
    "⛏️ Minecraft has various types of ores, each with unique uses.",
    "🎮 The game has a creative mode for unlimited building possibilities.",
    "🔧 Players can build complex machines and contraptions using redstone.",
    "🌦️ Minecraft has a dynamic weather system that affects gameplay.",
    "👾 The game has various types of mobs, each with unique behaviors.",
    "🌋 Players can explore vast underground cave systems.",
    "🧱 Minecraft has a variety of decorative blocks for building.",
    "🎮 The game's modding community has created custom content and enhancements.",
    "🚂 Players can use minecarts and rails for transportation.",
    "🌐 Minecraft has a thriving online multiplayer community.",
    "🌿 The game has various types of plants and crops for farming.",
    "🛒 Players can trade with villagers for valuable items.",
    "⚔️ Minecraft has a complex combat system with different weapons and tactics.",
    "🔮 The game's enchanting system allows for powerful upgrades.",
    "🗺️ Players can create custom maps and share them with others.",
    "🎶 Minecraft has a rich and immersive sound design.",
    "🧱 The game has various types of blocks, each with unique properties.",
    "🧭 Players can explore abandoned mineshafts and dungeons.",
    "💡 Minecraft has a detailed and realistic lighting system.",
    "🛠️ The game's resource management mechanics add depth to gameplay.",
    "🛡️ Players can create and customize banners for decoration.",
    "🌍 Minecraft has a variety of biomes, each with unique flora and fauna.",
    "🔧 The game's redstone mechanics allow for complex circuitry and automation.",
    "🎨 Players can create custom skins for their characters.",
    "⛏️ Minecraft has various types of ores, each with unique uses.",
    "🎮 The game has a creative mode for unlimited building possibilities.",
    "🔧 Players can build complex machines and contraptions using redstone.",
    "🌦️ Minecraft has a dynamic weather system that affects gameplay.",
    "👾 The game has various types of mobs, each with unique behaviors.",
    "🌋 Players can explore vast underground cave systems.",
    "🧱 Minecraft has a variety of decorative blocks for building.",
    "🎮 The game's modding community has created custom content and enhancements.",
    "🚂 Players can use minecarts and rails for transportation.",
    "🌐 Minecraft has a thriving online multiplayer community.",
    "🌿 The game has various types of plants and crops for farming.",
    "🛒 Players can trade with villagers for valuable items.",
    "⚔️ Minecraft has a complex combat system with different weapons and tactics.",
    "🔮 The game's enchanting system allows for powerful upgrades.",
    "🗺️ Players can create custom maps and share them with others.",
    "🎶 Minecraft has a rich and immersive sound design.",
    "🧱 The game has various types of blocks, each with unique properties.",
    "🧭 Players can explore abandoned mineshafts and dungeons.",
    "💡 Minecraft has a detailed and realistic lighting system.",
    "🛠️ The game's resource management mechanics add depth to gameplay.",
    "🛡️ Players can create and customize banners for decoration.",
    "🌍 Minecraft has a variety of biomes, each with unique flora and fauna.",
    "🔧 The game's redstone mechanics allow for complex circuitry and automation.",
    "🎨 Players can create custom skins for their characters.",
    "⛏️ Minecraft has various types of ores, each with unique uses.",
    "🎮 The game has a creative mode for unlimited building possibilities.",
    "🔧 Players can build complex machines and contraptions using redstone.",
    "🌦️ Minecraft has a dynamic weather system that affects gameplay.",
    "👾 The game has various types of mobs, each with unique behaviors.",
    "🌋 Players can explore vast underground cave systems.",
    "🧱 Minecraft has a variety of decorative blocks for building.",
    "🎮 The game's modding community has created custom content and enhancements.",
    "🚂 Players can use minecarts and rails for transportation.",
    "🌐 Minecraft has a thriving online multiplayer community.",
    "🌿 The game has various types of plants and crops for farming.",
    "🛒 Players can trade with villagers for valuable items.",
    "⚔️ Minecraft has a complex combat system with different weapons and tactics.",
    "🔮 The game's enchanting system allows for powerful upgrades.",
    "🗺️ Players can create custom maps and share them with others.",
    "🎶 Minecraft has a rich and immersive sound design.",
    "🧱 The game has various types of blocks, each with unique properties.",
    "🧭 Players can explore abandoned mineshafts and dungeons.",
    "💡 Minecraft has a detailed and realistic lighting system.",
    "🛠️ The game's resource management mechanics add depth to gameplay.",
    "🛡️ Players can create and customize banners for decoration.",
    "🌍 Minecraft has a variety of biomes, each with unique flora and fauna.",
    "🔧 The game's redstone mechanics allow for complex circuitry and automation.",
    "🎨 Players can create custom skins for their characters.",
    "⛏️ Minecraft has various types of ores, each with unique uses.",
    "🎮 The game has a creative mode for unlimited building possibilities.",
    "🔧 Players can build complex machines and contraptions using redstone.",
    "🌦️ Minecraft has a dynamic weather system that affects gameplay.",
    "👾 The game has various types of mobs, each with unique behaviors.",
    "🌋 Players can explore vast underground cave systems.",
    "🧱 Minecraft has a variety of decorative blocks for building.",
    "🎮 The game's modding community has created custom content and enhancements.",
    "🚂 Players can use minecarts and rails for transportation.",
    "🌐 Minecraft has a thriving online multiplayer community.",
    "🌿 The game has various types of plants and crops for farming.",
    "🛒 Players can trade with villagers for valuable items.",
    "⚔️ Minecraft has a complex combat system with different weapons and tactics.",
    "🔮 The game's enchanting system allows for powerful upgrades.",
    "🗺️ Players can create custom maps and share them with others.",
    "🎶 Minecraft has a rich and immersive sound design.",
    "🧱 The game has various types of blocks, each with unique properties.",
    "🧭 Players can explore abandoned mineshafts and dungeons.",
    "💡 Minecraft has a detailed and realistic lighting system.",
    "🛠️ The game's resource management mechanics add depth to gameplay.",
    "🛡️ Players can create and customize banners for decoration.",
    "🌍 Minecraft has a variety of biomes, each with unique flora and fauna.",
    "🔧 The game's redstone mechanics allow for complex circuitry and automation.",
    "🎨 Players can create custom skins for their characters.",
    "⛏️ Minecraft has various types of ores, each with unique uses.",
    "🎮 The game has a creative mode for unlimited building possibilities.",
    "🔧 Players can build complex machines and contraptions using redstone.",
    "🌦️ Minecraft has a dynamic weather system that affects gameplay.",
    "👾 The game has various types of mobs, each with unique behaviors.",
    "🌋 Players can explore vast underground cave systems.",
    "🧱 Minecraft has a variety of decorative blocks for building.",
    "🎮 The game's modding community has created custom content and enhancements.",
    "🚂 Players can use minecarts and rails for transportation.",
    "🌐 Minecraft has a thriving online multiplayer community.",
    "🌿 The game has various types of plants and crops for farming.",
    "🛒 Players can trade with villagers for valuable items.",
    "⚔️ Minecraft has a complex combat system with different weapons and tactics.",
    "🔮 The game's enchanting system allows for powerful upgrades.",
    "🗺️ Players can create custom maps and share them with others.",
    "🎶 Minecraft has a rich and immersive sound design.",
    "🧱 The game has various types of blocks, each with unique properties.",
    "🧭 Players can explore abandoned mineshafts and dungeons.",
    "💡 Minecraft has a detailed and realistic lighting system.",
    "🛠️ The game's resource management mechanics add depth to gameplay.",
    "🛡️ Players can create and customize banners for decoration.",
    "🌍 Minecraft has a variety of biomes, each with unique flora and fauna.",
    "🔧 The game's redstone mechanics allow for complex circuitry and automation.",
    "🎨 Players can create custom skins for their characters.",
    "⛏️ Minecraft has various types of ores, each with unique uses.",
    "🎮 The game has a creative mode for unlimited building possibilities.",
    "🔧 Players can build complex machines and contraptions using redstone.",
    "🌦️ Minecraft has a dynamic weather system that affects gameplay.",
    "👾 The game has various types of mobs, each with unique behaviors.",
    "🌋 Players can explore vast underground cave systems.",
    "🧱 Minecraft has a variety of decorative blocks for building.",
    "🎮 The game's modding community has created custom content and enhancements.",
    "🚂 Players can use minecarts and rails for transportation.",
    "🌐 Minecraft has a thriving online multiplayer community.",
    "🌿 The game has various types of plants and crops for farming"]
